name: ML Pipeline

on: [push]

jobs:
  model-evaluation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Build and start containers
      run: |
        docker-compose up -d --build
        
    - name: Wait for services
      run: sleep 30
        
    - name: Train model
      run: |
        docker exec dynamic_premium_prediction-flask_app-1 python src/train.py
        
    - name: Get metrics
      run: |
        docker exec dynamic_premium_prediction-flask_app-1 cat /tmp/metrics.json > metrics.json

    - name: Display Model Metrics
      run: |
        echo "## Model Performance Metrics" >> $GITHUB_STEP_SUMMARY
        cat metrics.json | jq -r '. | "R² Score: \(.r2)\nRMSE: \(.rmse)\nMSE: \(.mse)"' >> $GITHUB_STEP_SUMMARY
        echo "## Best Parameters" >> $GITHUB_STEP_SUMMARY
        cat metrics.json | jq -r '.best_params' >> $GITHUB_STEP_SUMMARY
        
    - name: Download MLflow artifacts
      run: |
        mkdir -p model_artifacts
        docker cp dynamic_premium_prediction-mlflow-1:/mlflow/mlartifacts/. model_artifacts/

    - name: Upload model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: model_artifacts/
        
    - name: Upload metrics artifact
      uses: actions/upload-artifact@v2
      with:
        name: model-metrics
        path: metrics.json
        
    - name: Clean up
      if: always()
      run: docker-compose down -v