name: ML Pipeline

on: [push]

jobs:
  model-evaluation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Wait for services
      run: |
        sleep 30
        docker ps
        
    - name: Train model
      run: |
        docker exec dynamic_premium_prediction-flask_app-1 python src/train.py
        
    - name: Get metrics
      run: |
        docker exec dynamic_premium_prediction-flask_app-1 cat /tmp/metrics.json > metrics.json

    - name: Display Model Metrics
      run: |
        echo "## Model Performance Metrics" >> $GITHUB_STEP_SUMMARY
        cat metrics.json | jq -r '. | "R² Score: \(.r2)\nRMSE: \(.rmse)\nMSE: \(.mse)"' >> $GITHUB_STEP_SUMMARY
        echo "## Best Parameters" >> $GITHUB_STEP_SUMMARY
        cat metrics.json | jq -r '.best_params' >> $GITHUB_STEP_SUMMARY
        
    - name: Clean up
      if: always()
      run: docker-compose down -v